Add camera
letsbuilda/pyweek36 pull request #33
Opened 2023-09-22 03:16 UTC by ilcheese2

2023-09-22 03:37 UTC, n0Oo0Oo0b requested changes

2023-09-22 03:37 UTC, n0Oo0Oo0b commented on pyweek36/main.py
> +        self.camera.move_to(
https://github.com/letsbuilda/pyweek36/blob/main/pyweek36/main.py#L155-L156

Moving the camera will offset the cursor position, so you'll have to adjust for that in the bullet angle calculation too

2023-09-22 03:37 UTC, n0Oo0Oo0b commented on pyweek36/main.py
> +                max(self.player_sprite.center_y - self.camera.viewport_height / 2, 0),
The current camera movement is quite sharp, I think adding some damping could help

We could also add a deadzone so the camera doesn't move every time you move/jump, and lookahead on the x axis

2023-09-22 05:15 UTC, n0Oo0Oo0b commented on pyweek36/constants.py
> +CAMERA_DAMPING = 0.8
I think 0.8 is quite hard to notice, from my testing somewhere around 0.15-0.3 feels a lot more natural

2023-09-23 06:13 UTC, n0Oo0Oo0b submitted a review, later dismissed
Looks alright to me, but another review from someone else won't hurt since I made some changes myself

2023-09-23 06:44 UTC, Anonymous4045 commented
There's some conflicts

2023-09-23 06:52 UTC, n0Oo0Oo0b commented
> There's some conflicts

Resolved

2023-09-23 12:13 UTC, n0Oo0Oo0b approved these changes
LGTM I guess

2023-09-23 12:13 UTC, merged